CREATE TABLE CUSTOMER (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL,
    email_address VARCHAR(256) NOT NULL,
    date_of_birth DATE NOT NULL,
    CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (id),
    CONSTRAINT UC_EMAIL_ADDRESS UNIQUE (email_address)
);

CREATE TABLE REDEMPTION_HISTORY (
    customer_id INTEGER NOT NULL,
    coupon_code VARCHAR(10) NOT NULL,
    territory VARCHAR(256) NOT NULL,
    is_winner CHAR(1) NOT NULL,
    redemption_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_COUPON_CODE PRIMARY KEY (coupon_code),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE TERRITORY (
    id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    win_period INTEGER NOT NULL,
    max_balls INTEGER NOT NULL,
    max_balls_per_day INTEGER NOT NULL,
    CONSTRAINT PK_TERRITORY_ID PRIMARY KEY (id),
    CONSTRAINT UC_TERRITORY_NAME UNIQUE (name)
);

CREATE TABLE TERRITORY_STATUS (
    territory_id INTEGER NOT NULL,
    redeems_after_win INTEGER NOT NULL,
    wins_today INTEGER NOT NULL,
    wins_total INTEGER NOT NULL,
    modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_TERRITORY_ID FOREIGN KEY (territory_id) REFERENCES territory(id),
    CONSTRAINT UC_TERRITORY_ID UNIQUE (territory_id)
);
